import unittest
from unittest.mock import patch

from app.document_processing.chunking import build_document_chunks
from app.document_processing.models import (
    BoundingBox,
    DocumentTable,
    TableCell,
    TableRow,
    UnifiedDocument,
)
from app.document_processing.table_stitching import (
    stitch_tables,
    stitch_tables_fail_open,
)

COLUMN_BOXES = ((0.05, 0.52), (0.60, 0.75), (0.80, 0.95))


def make_row(values: list[str], top: float, row_index: int = 0) -> TableRow:
    return TableRow(
        cells=[
            TableCell(
                text=value,
                row_index=row_index,
                column_index=column_index,
                bounding_box=BoundingBox(
                    left=left,
                    top=top,
                    right=right,
                    bottom=top + 0.03,
                ),
            )
            for column_index, (value, (left, right)) in enumerate(
                zip(values, COLUMN_BOXES, strict=True)
            )
        ]
    )


def make_table(
    table_id: str,
    page_number: int,
    title: str,
    top: float,
    bottom: float,
    labels: list[str],
    headers: list[str] | None = None,
) -> DocumentTable:
    header_rows = [make_row(headers, top)] if headers else []
    body_rows = [
        make_row(
            [label, str(100 + index), str(90 + index)],
            top + 0.08 + index * 0.04,
            index + 1,
        )
        for index, label in enumerate(labels)
    ]
    return DocumentTable(
        id=table_id,
        page_number=page_number,
        title=title,
        header_rows=header_rows,
        body_rows=body_rows,
        bounding_box=BoundingBox(left=0.05, top=top, right=0.95, bottom=bottom),
        source_processors=["form"],
        source_refs=[table_id],
    )


class TableStitchingRuleTests(unittest.TestCase):
    def test_twenty_labeled_adjacent_page_candidates(self):
        cases = [
            (
                "balance-assets",
                "Balance Sheets",
                "Current assets",
                "Balance Sheets",
                "Non-current assets",
                True,
            ),
            (
                "balance-liabilities",
                "Balance Sheets",
                "Current liabilities",
                "Balance Sheets",
                "Shareholders equity",
                True,
            ),
            (
                "cash-operating",
                "Statements of Cash Flows",
                "Operating activities",
                "Statements of Cash Flows",
                "Investing activities",
                True,
            ),
            (
                "cash-financing",
                "Statements of Cash Flows",
                "Investing activities",
                "Statements of Cash Flows",
                "Financing activities",
                True,
            ),
            (
                "operations-sales",
                "Statements of Operations",
                "Net sales",
                "Statements of Operations",
                "Gross margin",
                True,
            ),
            (
                "operations-income",
                "Statements of Operations",
                "Operating income",
                "Statements of Operations",
                "Net income",
                True,
            ),
            (
                "segment-geography",
                "Reportable segment",
                "Americas",
                "Reportable segment",
                "Greater China",
                True,
            ),
            (
                "segment-products",
                "Product category",
                "iPhone",
                "Product category",
                "Services",
                True,
            ),
            (
                "balance-sections",
                "Balance Sheets",
                "Total current assets",
                "Balance Sheets",
                "Current liabilities",
                True,
            ),
            (
                "cash-sections",
                "Statements of Cash Flows",
                "Cash generated by operating activities",
                "Statements of Cash Flows",
                "Financing activities",
                True,
            ),
            (
                "operations-balance",
                "Statements of Operations",
                "Net income",
                "Balance Sheets",
                "Current assets",
                False,
            ),
            (
                "balance-cash",
                "Balance Sheets",
                "Total assets",
                "Statements of Cash Flows",
                "Operating activities",
                False,
            ),
            (
                "cash-segment",
                "Statements of Cash Flows",
                "Financing activities",
                "Reportable segment",
                "Americas",
                False,
            ),
            (
                "segment-operations",
                "Reportable segment",
                "Greater China",
                "Statements of Operations",
                "Net sales",
                False,
            ),
            (
                "operations-cash",
                "Statements of Operations",
                "Gross margin",
                "Statements of Cash Flows",
                "Investing activities",
                False,
            ),
            (
                "balance-segment",
                "Balance Sheets",
                "Shareholders equity",
                "Product category",
                "Services",
                False,
            ),
            (
                "cash-balance",
                "Statements of Cash Flows",
                "Cash equivalents",
                "Balance Sheets",
                "Current liabilities",
                False,
            ),
            (
                "segment-cash",
                "Reportable segment",
                "Americas",
                "Statements of Cash Flows",
                "Operating activities",
                False,
            ),
            (
                "operations-segment",
                "Statements of Operations",
                "Operating income",
                "Product category",
                "iPhone",
                False,
            ),
            (
                "balance-operations",
                "Balance Sheets",
                "Non-current assets",
                "Statements of Operations",
                "Net income",
                False,
            ),
        ]

        for (
            case_id,
            first_title,
            first_label,
            second_title,
            second_label,
            expected,
        ) in cases:
            with self.subTest(case_id=case_id):
                first = make_table(
                    f"{case_id}-first",
                    1,
                    first_title,
                    0.45,
                    0.95,
                    [first_label],
                    ["Item", "2025", "2024"],
                )
                second = make_table(
                    f"{case_id}-second",
                    2,
                    second_title,
                    0.05,
                    0.60,
                    [second_label],
                    ["Item", "2025", "2024"],
                )

                result = stitch_tables([first, second], [], minimum_score=0.75)

                self.assertEqual(result.stitched_table_count == 1, expected)

    def test_merges_adjacent_financial_table_with_repeated_header(self):
        first = make_table(
            "p15-assets",
            15,
            "Balance Sheets",
            0.45,
            0.96,
            ["Current assets", "Total current assets"],
            ["Item", "2025", "2024"],
        )
        second = make_table(
            "p16-assets",
            16,
            "Balance Sheets",
            0.04,
            0.60,
            ["Non-current assets", "Total assets"],
            ["Item", "2025", "2024"],
        )

        result = stitch_tables([first, second], [], minimum_score=0.75)

        self.assertEqual(result.logical_table_count, 1)
        self.assertEqual(result.stitched_table_count, 1)
        logical = result.logical_tables[0]
        self.assertEqual((logical.page_start, logical.page_end), (15, 16))
        self.assertEqual(logical.source_table_ids, ["p15-assets", "p16-assets"])
        self.assertEqual(
            [row.source_page_number for row in logical.body_rows],
            [15, 15, 16, 16],
        )
        self.assertTrue(result.decisions[0].matched)

    def test_merges_without_repeated_header_when_structure_and_context_match(self):
        first = make_table(
            "p1-cash",
            1,
            "Statements of Cash Flows",
            0.40,
            0.94,
            ["Operating activities", "Cash generated by operating activities"],
            ["Item", "2025", "2024"],
        )
        second = make_table(
            "p2-cash",
            2,
            "Statements of Cash Flows",
            0.05,
            0.65,
            ["Investing activities", "Purchases of marketable securities"],
            None,
        )

        result = stitch_tables([first, second], [], minimum_score=0.75)

        self.assertEqual(result.logical_table_count, 1)
        self.assertTrue(result.decisions[0].matched)

    def test_rejects_different_financial_statements_with_same_columns(self):
        operations = make_table(
            "operations",
            1,
            "Statements of Operations",
            0.45,
            0.95,
            ["Net sales", "Net income"],
            ["Item", "2025", "2024"],
        )
        balance_sheet = make_table(
            "balance-sheet",
            2,
            "Balance Sheets",
            0.05,
            0.65,
            ["Current assets", "Total assets"],
            ["Item", "2025", "2024"],
        )

        result = stitch_tables([operations, balance_sheet], [], minimum_score=0.75)

        self.assertEqual(result.logical_table_count, 2)
        self.assertIn(
            "financial_statement_type_conflict",
            result.decisions[0].rejection_reasons,
        )

    def test_rejects_year_conflict_and_non_edge_tables(self):
        first = make_table(
            "first",
            1,
            "Balance Sheets 2025",
            0.45,
            0.95,
            ["Current assets"],
            ["Item", "2025", "2024"],
        )
        conflicting = make_table(
            "conflicting",
            2,
            "Balance Sheets 2023",
            0.05,
            0.60,
            ["Non-current assets"],
            ["Item", "2023", "2022"],
        )
        result = stitch_tables([first, conflicting], [], minimum_score=0.75)
        self.assertIn("reporting_year_conflict", result.decisions[0].rejection_reasons)

        not_at_edge = make_table(
            "middle",
            2,
            "Balance Sheets 2025",
            0.40,
            0.80,
            ["Non-current assets"],
            ["Item", "2025", "2024"],
        )
        no_candidate = stitch_tables([first, not_at_edge], [], minimum_score=0.75)
        self.assertEqual(no_candidate.decisions, [])
        self.assertEqual(no_candidate.logical_table_count, 2)

    def test_builds_three_page_chain_without_branching(self):
        tables = [
            make_table(
                f"cash-{page}",
                page,
                "Statements of Cash Flows",
                0.45 if page == 1 else 0.05,
                0.95,
                [f"Operating activities {page}", "Cash equivalents"],
                ["Item", "2025", "2024"],
            )
            for page in (1, 2, 3)
        ]

        result = stitch_tables(tables, [], minimum_score=0.75)

        self.assertEqual(result.logical_table_count, 1)
        self.assertEqual(
            result.logical_tables[0].source_table_ids, ["cash-1", "cash-2", "cash-3"]
        )
        self.assertEqual(sum(decision.matched for decision in result.decisions), 2)

    def test_deduplicates_repeated_boundary_row(self):
        first = make_table(
            "first",
            1,
            "Balance Sheets",
            0.45,
            0.95,
            ["Current assets", "Total current assets"],
            ["Item", "2025", "2024"],
        )
        second = make_table(
            "second",
            2,
            "Balance Sheets",
            0.05,
            0.60,
            ["Total current assets", "Non-current assets"],
            ["Item", "2025", "2024"],
        )
        second.body_rows[0] = first.body_rows[-1].model_copy(deep=True)

        result = stitch_tables([first, second], [], minimum_score=0.75)

        labels = [row.cells[0].text for row in result.logical_tables[0].body_rows]
        self.assertEqual(labels.count("Total current assets"), 1)

    def test_removes_header_misclassified_as_first_body_row(self):
        first = make_table(
            "first",
            1,
            "Balance Sheets",
            0.45,
            0.95,
            ["Current assets"],
            ["Item", "2025", "2024"],
        )
        second = make_table(
            "second",
            2,
            "Balance Sheets",
            0.05,
            0.60,
            ["Non-current assets"],
            None,
        )
        repeated_header = first.header_rows[0].model_copy(deep=True)
        second.body_rows.insert(0, repeated_header)

        result = stitch_tables([first, second], [], minimum_score=0.75)

        labels = [row.cells[0].text for row in result.logical_tables[0].body_rows]
        self.assertNotIn("Item", labels)

    def test_disabled_stitching_keeps_physical_tables(self):
        first = make_table(
            "first",
            1,
            "Balance Sheets",
            0.45,
            0.95,
            ["Current assets"],
            ["Item", "2025", "2024"],
        )
        second = make_table(
            "second",
            2,
            "Balance Sheets",
            0.05,
            0.60,
            ["Non-current assets"],
            ["Item", "2025", "2024"],
        )

        result = stitch_tables([first, second], [], enabled=False)

        self.assertEqual(result.logical_table_count, 2)
        self.assertEqual(result.stitched_table_count, 0)
        self.assertEqual(result.decisions, [])

    def test_failure_falls_back_to_single_page_tables(self):
        table = make_table(
            "table-1",
            1,
            "Balance Sheets",
            0.40,
            0.90,
            ["Total assets"],
            ["Item", "2025", "2024"],
        )
        with patch(
            "app.document_processing.table_stitching.stitch_tables",
            side_effect=RuntimeError("broken rule"),
        ):
            result = stitch_tables_fail_open([table], [])

        self.assertEqual(result.logical_table_count, 1)
        self.assertEqual(result.logical_tables[0].id, "table-1")
        self.assertIn("broken rule", result.warnings[0])


class LogicalTableChunkingTests(unittest.TestCase):
    def test_cross_page_chunk_contains_provenance_and_repeated_header(self):
        first = make_table(
            "first",
            1,
            "Balance Sheets",
            0.45,
            0.95,
            ["Current assets", "Total current assets"],
            ["Item", "2025", "2024"],
        )
        second = make_table(
            "second",
            2,
            "Balance Sheets",
            0.05,
            0.60,
            ["Non-current assets", "Total assets"],
            ["Item", "2025", "2024"],
        )
        stitching = stitch_tables([first, second], [], minimum_score=0.75)
        document = UnifiedDocument(
            file_id=99,
            filename="report.pdf",
            page_count=2,
            tables=[first, second],
        )

        chunks = build_document_chunks(
            document,
            "default",
            "user-1",
            chunk_size=180,
            logical_tables=stitching.logical_tables,
        )
        table_chunks = [
            chunk for chunk in chunks if chunk["metadata"]["content_type"] == "table"
        ]

        self.assertGreater(len(table_chunks), 1)
        for chunk in table_chunks:
            metadata = chunk["metadata"]
            self.assertIn("Item", chunk["content"])
            self.assertIn("页码：1-2", chunk["content"])
            self.assertTrue(metadata["is_cross_page"])
            self.assertEqual(metadata["source_table_ids"], ["first", "second"])
            self.assertEqual((metadata["page_start"], metadata["page_end"]), (1, 2))
            self.assertTrue(metadata["row_source_pages"])

    def test_single_page_logical_table_keeps_physical_id(self):
        table = make_table(
            "single",
            1,
            "Financial metrics",
            0.20,
            0.60,
            ["Revenue"],
            ["Item", "2025", "2024"],
        )
        stitching = stitch_tables([table], [], minimum_score=0.75)
        document = UnifiedDocument(
            file_id=3,
            filename="report.pdf",
            page_count=1,
            tables=[table],
        )

        chunks = build_document_chunks(
            document,
            "default",
            "user-1",
            logical_tables=stitching.logical_tables,
        )

        table_chunk = next(
            chunk for chunk in chunks if chunk["metadata"]["content_type"] == "table"
        )
        self.assertEqual(table_chunk["metadata"]["source_id"], "single")
        self.assertEqual(
            table_chunk["metadata"]["chunk_id"],
            "file-3-table-single-0",
        )


if __name__ == "__main__":
    unittest.main()
